### ISSUE TITLE
CPVIA: Harmonizer Does Not Work in Democratic Mode at All

### ISSUE THREAD

**Issue by jordanhenshaw** [Alva-Theaters/Sorcerer#75]

**Comment by jordanhenshaw** [comment]
I just tested this again and could not immediately reproduce. So maybe it wasn't actually as bad as I thought it was.

**Comment by jordanhenshaw** [comment]
I reproduced in the original file:

Error in bpy.app.handlers.frame_change_post[0]:
Traceback (most recent call last):
  File "/Users/easystreetphotography1/Library/Application Support/Blender/4.2/scripts/addons/Sorcerer/event_manager.py", line 620, in on_frame_change_post
    event_manager_instance.publish_pending_cpvia_requests(scene)
  File "/Users/easystreetphotography1/Library/Application Support/Blender/4.2/scripts/addons/Sorcerer/event_manager.py", line 559, in publish_pending_cpvia_requests
    no_conflicts = Harmonizer.democracy(no_duplicates)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File REDACTED
Support/Blender/4.2/scripts/addons/Sorcerer/cpvia/harmonizer.py", line 59, in democracy
    request_dict[key]['weighted_sum'] += v * i
TypeError: unsupported operand type(s) for +=: 'int' and 'tuple'

**Comment by jordanhenshaw** [comment]
Fixed with 4ca22739302f81a59fbc461a2cd3cc5a058cd413

This was happening because of color values being handled as integers.
